replicaCount: 1

image:
  repository: shanmukhkasilanka/sample-app
  tag: 0.0.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: sample-app.example.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
